18 internal links
Roxha-V/PTGA-Landing pull request #20
Opened 2024-04-30 13:49 UTC by Roxha-V

Cambios pequeños en estilo general - Smooth behavior para la aplicacion general -  Manejador de eventos para secciones de aplicacion.-
    Se resuelven pequeños problemas de estilo en cuanto a los tamaños de los textos con respecto a responsive sizes. Se agrega smooth behavior para todo el scroll general de la aplicacion y en particular se intenta avanzar con el manejador de evento click en los items del navbar para que estos se linkeen con las secciones correspondientes. Esto se encuentra en proceso.

2024-04-30 16:21 UTC, devPalta reviewed
resolver los cambios de review y realizar el rebase con develop que esta actualizado con boton flotante

2024-04-30 16:21 UTC, devPalta commented on app/components/about-us-section/index.jsx
> +                <p className={`${montserrat.className} object-contain font-sans xs:px-20 px-40 xs:text-lg md:text-[1.25rem] md:leading-normal lg:text-[2.25rem] lg:leading-loose text-white text-justif
cambio fuera de scope/alcance de la tarea, no añadirlos

2024-04-30 16:21 UTC, devPalta commented on app/components/navbar-component/index.jsx
> +                        console.log('se clickea seccion')
eliminar console log

2024-04-30 16:21 UTC, devPalta commented on app/components/navbar-component/index.jsx
> +                        document.getElementById(item.id).scrollIntoView({ behavior: 'smooth' });
la implementacion no funciona 
![chrome-capture-2024-4-30](https://github.com/Roxha-V/PTGA-Landing/assets/87544205/843a2bac-b2b8-44cf-9ffa-3f6e546bad5e)

2024-04-30 16:21 UTC, devPalta commented on tailwind.config.js
> +      },
cambio fuera del scope/alcance de la task

2024-05-02 18:01 UTC, Roxha-V commented
Se agrega funcion scrollToSection que  se encarga de desplazar la ventana de visualización del navegador suavemente hasta el elemento cuyo Id coincida con el que se pasa como argumento. Esto se logra utilizando el método scrollIntoView .  Hay que asegurarse de que las secciones tengan un id que coincida con los que se definen en arreglo navbarItems. A mejorar implementancion por si ese array se cambia en algun momento. Listo para revision @devPalta

2024-05-02 18:15 UTC, Roxha-V commented on app/components/navbar-component/index.jsx
> +                        console.log('se clickea seccion')
eliminado

2024-05-02 18:16 UTC, Roxha-V commented on app/components/about-us-section/index.jsx
> +                <p className={`${montserrat.className} object-contain font-sans xs:px-20 px-40 xs:text-lg md:text-[1.25rem] md:leading-normal lg:text-[2.25rem] lg:leading-loose text-white text-justif
realizado, pero se hara un comnetario abajo para asignar y resolver tarea de tamaños textos

2024-05-02 18:16 UTC, Roxha-V commented on app/components/navbar-component/index.jsx
> +                        document.getElementById(item.id).scrollIntoView({ behavior: 'smooth' });
resuelto

2024-05-02 20:24 UTC, devPalta requested changes

2024-05-02 20:24 UTC, devPalta commented on app/components/navbar-component/index.jsx
> +                      onClick={() => scrollToSection(id)}
id no esta definido en este punto, revisar deberia ser item.id

2024-05-13 18:34 UTC, Roxha-V commented on app/components/navbar-component/index.jsx
> +                      onClick={() => scrollToSection(id)}
resuelto gg

2024-05-13 18:46 UTC, Roxha-V commented
@devPalta 

- Se resuelve el issue #18

- Se mejora la implementación del desplazamiento suave utilizando solo JavaScript y eliminando CSS global.

**- Se sugiere reintroducir el CSS global para el comportamiento de desplazamiento suave para garantizar una experiencia de desplazamiento suave consistente y predeterminada.**

- Una futura mejora puede ser corregir la función scrollToSection, donde el comportamiento del desplazamiento suave no funciona como se espera. La causa raíz del problema aún no ha sido identificada y resuelta.

2024-05-17 13:53 UTC, devPalter commented on app/components/navbar-component/index.jsx
> +                    <a className="sections text-white text-xl" href={`#${item.id}`}
check <a> tag this preserve old implementation with css, can be replace with other?

2024-05-17 14:01 UTC, devPalta commented on app/components/navbar-component/index.jsx
> +                <a className="border-2 hover:border-indigo-800" href={`#${item.id}`}
mobile menu is not scrolling smooth, bear in mind implement same change in both

2024-05-17 14:04 UTC, devPalta commented on app/components/navbar-component/index.jsx
> +      <div className="drawer-side z-40">  {/* aca arranca la parte del drawer que se muestra en mobile y pantallas chicas ocultando lo anterior */}
change out of scope

2024-05-20 17:06 UTC, Roxha-V commented
Resolved change that was out of scope. I got confused in the commit :/ and it was branch 22 not 21. An amen is made to change the last commit correctly.

2024-05-21 14:00 UTC, devPalta commented on app/layout.js
> +      <body className="scroll-smooth focus:scroll-auto">
change out of scope

2024-05-21 15:04 UTC, devPalta approved these changes

2024-05-21 15:04 UTC, merged