#25_client_carousel_component
Roxha-V/PTGA-Landing pull request #31
Opened 2024-05-28 17:58 UTC by Roxha-V

implementation of carousel component for client- carousel section. Swiper library is used. New tasks (as a propousal) may be: to edit carousel style, and differentiating the category of component and section in this and other elements of the app.

2024-05-29 16:46 UTC, devPalta requested changes

2024-05-29 16:46 UTC, devPalter commented on public/img/logo6.jpg
estos logos van a ser usados?

2024-05-29 16:46 UTC, devPalter commented on app/components/clients_carousel/index.jsx
> +    <div className="w-full h-full">
falta añadir id de la seccion para navegación interna

2024-05-29 16:47 UTC, devPalta commented
Luego de las correciones hacer un rebase de los commits en 1 solo

2024-05-30 12:43 UTC, Roxha-V commented on public/img/logo6.jpg
logo images are not necessary, they were used as an example to finish the structure of the carousel. They will be deleted from the project.

2024-05-30 14:34 UTC, Roxha-V commented
The revised changes are resolved, rebase is made to develop and all the commits are merged into one. Last revision is requested to be able to merge the branches.

2024-05-30 18:53 UTC, devPalta approved these changes

2024-05-30 18:53 UTC, devPalta commented on app/page.js
> +    <main className="min-h-screen justify-between">
why? is necesary?

2024-05-30 18:53 UTC, merged