27 improvement services section
Roxha-V/PTGA-Landing pull request #40
Opened 2024-06-04 10:48 UTC by Roxha-V

Fixed grid and card padding for small devices.

2024-06-04 13:33 UTC, devPalter requested changes

2024-06-04 13:33 UTC, devPalta commented on app/components/contact_section/index.jsx
> +    <div>
cambio que no acorde a la tarea

2024-06-04 13:33 UTC, devPalta commented on package.json
> +    "swiper": "^11.1.4"
cambio no acorde a la tarea

2024-06-04 14:46 UTC, Roxha-V commented
resuelto y comiteado . services cards review improvements and coments were resolved (grid /padding/shadow/styles)

2024-06-05 13:16 UTC, Roxha-V commented
rebase de la rama hecho  pero muestra la siguiente rta : remote: - 1 review requesting changes by reviewers with write access. [Requiere revisión de propietarios de código: Se necesita una revisión de al menos un propietario de código para los cambios en la rama develop.]

2024-06-05 15:51 UTC, devPalta approved these changes

2024-06-05 15:51 UTC, merged