41 contact section validation
Roxha-V/PTGA-Landing pull request #45
Opened 2024-06-08 17:43 UTC by Roxha-V

A test was made to test the functionality of the component Finaly the changes from the validation test were integrated into the real code with the already established styles.

2024-06-10 12:00 UTC, devPalta commented
corregir que pr este apuntando a develop

2024-06-10 21:25 UTC, Roxha-V commented
@devPalta  listou

2024-06-12 19:03 UTC, devPalta requested changes

2024-06-12 19:03 UTC, devPalta commented on app/components/contact_section/index.jsx
> +  console.log(formState);
remove log

2024-06-12 19:16 UTC, Roxha-V commented
problem solved - i suggest an interactive rebase to develop, so i unnecesary commits will be eliminated and the commit history will be more clear.

2024-06-13 20:38 UTC, devPalta approved these changes

2024-06-13 20:47 UTC, merged